var binding = tabVendor.getBinding("items");
var filter = new sap.ui.model.Filter({
    filters: [
        new sap.ui.model.Filter("LIFNR", "Contains", this.getValue()),
        new sap.ui.model.Filter("NAME1", "Contains", this.getValue()),
        new sap.ui.model.Filter("PSTLZ", "Contains", this.getValue()),
        new sap.ui.model.Filter("ZITY", "Contains", this.getValue()),
    ],
    and: false
})
binding.filter([filter]);