oBusy.open();

apiinvoiceSave({
    data: [modelAppData.oData.invoice]
}).then(function () {

    apiworkflowStart({
        data: modelAppData.oData.invoice
    }).then(function (data) {
        oBusy.close();
        sap.m.MessageToast.show("Sent to approval");
        if (config.events.afterChildSave) config.events.afterChildSave();
        if (config.events.onChildBack) config.events.onChildBack();
    })

})

